import { IncidentData } from "./types";

export const MOCK_INCIDENTS: IncidentData[] = [
  {
    id: "OS-2026-IN",
    name: "Incident Alpha: Gulf of Mannar",
    locationName: "Gulf of Mannar, Indian Ocean",
    coordinates: "8°43'12\"N, 78°09'36\"E",
    detectedAt: "2026-03-02 04:15 UTC",
    slickArea: "14.62 km²",
    isUnknownSource: false,
    thresholdUsed: 60,
    backtrackHours: 12,
    windSpeed: "14.2 kn @ 045° (NE)",
    currentDrift: "0.48 m/s @ 238° (SW)",
    candidates: [
      {
        mmsi: "419001824",
        name: "MT OCEAN CONQUEROR",
        flag: "Liberia (LR)",
        type: "Crude Oil Tanker (VLCC)",
        score: 89.4,
        isCulprit: true,
        components: {
          spatial: 94,
          temporal: 91,
          heading: 88,
          origin: 93,
          aisQuality: 95,
          behaviour: 82,
        },
        notes: "Exact spatiotemporal intercept at T-11.4h within the 90% origin confidence ellipse. Speed dropped abruptly from 14.8 to 8.2 kn coincident with discharge, with AIS transponder gap lasting 24 min.",
      },
      {
        mmsi: "538006112",
        name: "MV SEA GULL",
        flag: "Panama (PA)",
        type: "Bulk Carrier",
        score: 44.2,
        isCulprit: false,
        components: {
          spatial: 58,
          temporal: 62,
          heading: 32,
          origin: 41,
          aisQuality: 78,
          behaviour: 35,
        },
        notes: "Mismatched heading vector (015° vs 235° drift). Crossed 4.2 km outside the reconstructed origin probability zone.",
      },
      {
        mmsi: "211334000",
        name: "STAR PRIDE",
        flag: "Germany (DE)",
        type: "Container Vessel",
        score: 28.1,
        isCulprit: false,
        components: {
          spatial: 34,
          temporal: 22,
          heading: 45,
          origin: 26,
          aisQuality: 90,
          behaviour: 18,
        },
        notes: "Temporal discordance. Transited corridor 9.5 hours prior to the estimated discharge window.",
      },
    ],
  },
  {
    id: "OS-2026-AR",
    name: "Incident Bravo: Arabian Sea (Off Mumbai)",
    locationName: "Arabian Sea, 48nm W of Mumbai",
    coordinates: "18°56'24\"N, 72°12'05\"E",
    detectedAt: "2026-03-01 11:30 UTC",
    slickArea: "8.90 km²",
    isUnknownSource: true,
    thresholdUsed: 60,
    backtrackHours: 16,
    windSpeed: "18.5 kn @ 310° (NW)",
    currentDrift: "0.62 m/s @ 142° (SE)",
    candidates: [
      {
        mmsi: "419099120",
        name: "MV COASTAL RUNNER",
        flag: "India (IN)",
        type: "General Cargo",
        score: 41.3,
        isCulprit: false,
        components: {
          spatial: 48,
          temporal: 42,
          heading: 39,
          origin: 40,
          aisQuality: 82,
          behaviour: 36,
        },
        notes: "Crossed corridor during window but closest approach was 6.8 km outside the 95% origin boundary.",
      },
      {
        mmsi: "352001449",
        name: "BLUE HORIZON",
        flag: "Marshall Islands (MH)",
        type: "Chemical Tanker",
        score: 33.7,
        isCulprit: false,
        components: {
          spatial: 31,
          temporal: 38,
          heading: 44,
          origin: 29,
          aisQuality: 74,
          behaviour: 26,
        },
        notes: "Maintained steady 16 knots without anomalous maneuvers; surface drift vector mismatch.",
      },
    ],
  },
];
